name: C Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2
    - name: dir
      run: "cd C:\\rogram Files\\"
    - name: dir2
      run: "dir"
    - name: Boot environment
      run: "\"c:\\rogram Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat\" amd64"
    - name: build
      run: "msbuild msvc/pelagia.sln"
